### ISSUE TITLE
Overview of next TODO

### ISSUE THREAD

**Issue by simlei** [simlei/org.cryptool.functionlist#18]
```
[x] - erledigt
[oo] - andauernd
[ ] - noch nicht begonnen
```

### Website:

**Legende**:

- [x] CT2: Funktion ist im Navigations-Bar verfügbar. ==> CT2: Funktion ist im oberen Navigations-Bar verfügbar.
- [x] CT2: Function is available in the navigation bar. ==> CT2: Function is available in the top navigation bar.

- [x] Postfixes erläutern:
    - [visual]              : Visualization of inner workings, e.g. via the presentation mode within a CT2 component
    - (PRNG)                : Pseudo random number generator
    - [attack or analysis]  : templates for breaking a function or protocol
    - [MPC]                 : Multi-party communication

- [ ] Schwebende Legende (toggle per schwebendem Button)
- [x] **Path count zzgl zu Group count**

### Spezifische Fehler in der Tabelle

- [ ] replace `(PRNG)` with `[PRNG]` for consistency with other tags

### Manuell gepflegte Datenlage

- [oo] **Einheitlichkeit aller Oberbegriffe, Pfade**
- [oo] **Generelle Korrektheit, jedoch ohne spezifische Überprüfung jedes einzelnen Eintrags am Programm**
- [ ] **CT1 Prüfung auf Vollständigkeit**
    - https://www.cryptool.org/en/ctp-documentation/ctbook S. 430/451
- [ ] CTO Prüfung auf Vollständigkeit

### Datenverarbeitung

- [x] `--` ==> `–` ( /home/simon/sandbox/featurelist/ct_functionlist/src/flist_step_tohtml.py )
- [ ] Unterschiedlich viele Einträge en/de auch CT2/JCT ( --> systematisch)

**Comment by simlei** [comment]
## Overview of standing issues that are urgent:

[ ] https://github.com/simlei/org.cryptool.functionlist/issues/15 (Website code / JS)

**Comment by simlei** [comment]
Schwebende Legende wird als nicht wichtig bzw. später erledigen abgelegt

**Comment by simlei** [comment]
this stays open until I get the oll korrekt, then I guess this is done :)
